# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bizzi/IC/teste/hbft-sdhash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bizzi/IC/teste/hbft-sdhash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bizzi/IC/teste/hbft-sdhash/CMakeFiles /home/bizzi/IC/teste/hbft-sdhash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bizzi/IC/teste/hbft-sdhash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mrsh_hbft

# Build rule for target.
mrsh_hbft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mrsh_hbft
.PHONY : mrsh_hbft

# fast build rule for target.
mrsh_hbft/fast:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/build
.PHONY : mrsh_hbft/fast

header/filehash.o: header/filehash.h.o

.PHONY : header/filehash.o

# target to build an object file
header/filehash.h.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/header/filehash.h.o
.PHONY : header/filehash.h.o

header/filehash.i: header/filehash.h.i

.PHONY : header/filehash.i

# target to preprocess a source file
header/filehash.h.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/header/filehash.h.i
.PHONY : header/filehash.h.i

header/filehash.s: header/filehash.h.s

.PHONY : header/filehash.s

# target to generate assembly for a file
header/filehash.h.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/header/filehash.h.s
.PHONY : header/filehash.h.s

src/bloomfilter.o: src/bloomfilter.c.o

.PHONY : src/bloomfilter.o

# target to build an object file
src/bloomfilter.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/bloomfilter.c.o
.PHONY : src/bloomfilter.c.o

src/bloomfilter.i: src/bloomfilter.c.i

.PHONY : src/bloomfilter.i

# target to preprocess a source file
src/bloomfilter.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/bloomfilter.c.i
.PHONY : src/bloomfilter.c.i

src/bloomfilter.s: src/bloomfilter.c.s

.PHONY : src/bloomfilter.s

# target to generate assembly for a file
src/bloomfilter.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/bloomfilter.c.s
.PHONY : src/bloomfilter.c.s

src/bloomfiltertree.o: src/bloomfiltertree.c.o

.PHONY : src/bloomfiltertree.o

# target to build an object file
src/bloomfiltertree.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/bloomfiltertree.c.o
.PHONY : src/bloomfiltertree.c.o

src/bloomfiltertree.i: src/bloomfiltertree.c.i

.PHONY : src/bloomfiltertree.i

# target to preprocess a source file
src/bloomfiltertree.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/bloomfiltertree.c.i
.PHONY : src/bloomfiltertree.c.i

src/bloomfiltertree.s: src/bloomfiltertree.c.s

.PHONY : src/bloomfiltertree.s

# target to generate assembly for a file
src/bloomfiltertree.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/bloomfiltertree.c.s
.PHONY : src/bloomfiltertree.c.s

src/filehash.o: src/filehash.c.o

.PHONY : src/filehash.o

# target to build an object file
src/filehash.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/filehash.c.o
.PHONY : src/filehash.c.o

src/filehash.i: src/filehash.c.i

.PHONY : src/filehash.i

# target to preprocess a source file
src/filehash.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/filehash.c.i
.PHONY : src/filehash.c.i

src/filehash.s: src/filehash.c.s

.PHONY : src/filehash.s

# target to generate assembly for a file
src/filehash.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/filehash.c.s
.PHONY : src/filehash.c.s

src/fingerprint.o: src/fingerprint.c.o

.PHONY : src/fingerprint.o

# target to build an object file
src/fingerprint.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fingerprint.c.o
.PHONY : src/fingerprint.c.o

src/fingerprint.i: src/fingerprint.c.i

.PHONY : src/fingerprint.i

# target to preprocess a source file
src/fingerprint.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fingerprint.c.i
.PHONY : src/fingerprint.c.i

src/fingerprint.s: src/fingerprint.c.s

.PHONY : src/fingerprint.s

# target to generate assembly for a file
src/fingerprint.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fingerprint.c.s
.PHONY : src/fingerprint.c.s

src/fingerprintList.o: src/fingerprintList.c.o

.PHONY : src/fingerprintList.o

# target to build an object file
src/fingerprintList.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fingerprintList.c.o
.PHONY : src/fingerprintList.c.o

src/fingerprintList.i: src/fingerprintList.c.i

.PHONY : src/fingerprintList.i

# target to preprocess a source file
src/fingerprintList.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fingerprintList.c.i
.PHONY : src/fingerprintList.c.i

src/fingerprintList.s: src/fingerprintList.c.s

.PHONY : src/fingerprintList.s

# target to generate assembly for a file
src/fingerprintList.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fingerprintList.c.s
.PHONY : src/fingerprintList.c.s

src/fnv.o: src/fnv.c.o

.PHONY : src/fnv.o

# target to build an object file
src/fnv.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fnv.c.o
.PHONY : src/fnv.c.o

src/fnv.i: src/fnv.c.i

.PHONY : src/fnv.i

# target to preprocess a source file
src/fnv.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fnv.c.i
.PHONY : src/fnv.c.i

src/fnv.s: src/fnv.c.s

.PHONY : src/fnv.s

# target to generate assembly for a file
src/fnv.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/fnv.c.s
.PHONY : src/fnv.c.s

src/hashing.o: src/hashing.c.o

.PHONY : src/hashing.o

# target to build an object file
src/hashing.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/hashing.c.o
.PHONY : src/hashing.c.o

src/hashing.i: src/hashing.c.i

.PHONY : src/hashing.i

# target to preprocess a source file
src/hashing.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/hashing.c.i
.PHONY : src/hashing.c.i

src/hashing.s: src/hashing.c.s

.PHONY : src/hashing.s

# target to generate assembly for a file
src/hashing.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/hashing.c.s
.PHONY : src/hashing.c.s

src/helper.o: src/helper.c.o

.PHONY : src/helper.o

# target to build an object file
src/helper.c.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/helper.c.o
.PHONY : src/helper.c.o

src/helper.i: src/helper.c.i

.PHONY : src/helper.i

# target to preprocess a source file
src/helper.c.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/helper.c.i
.PHONY : src/helper.c.i

src/helper.s: src/helper.c.s

.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.c.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/helper.c.s
.PHONY : src/helper.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sdhash.o: src/sdhash.cpp.o

.PHONY : src/sdhash.o

# target to build an object file
src/sdhash.cpp.o:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/sdhash.cpp.o
.PHONY : src/sdhash.cpp.o

src/sdhash.i: src/sdhash.cpp.i

.PHONY : src/sdhash.i

# target to preprocess a source file
src/sdhash.cpp.i:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/sdhash.cpp.i
.PHONY : src/sdhash.cpp.i

src/sdhash.s: src/sdhash.cpp.s

.PHONY : src/sdhash.s

# target to generate assembly for a file
src/sdhash.cpp.s:
	$(MAKE) -f CMakeFiles/mrsh_hbft.dir/build.make CMakeFiles/mrsh_hbft.dir/src/sdhash.cpp.s
.PHONY : src/sdhash.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mrsh_hbft"
	@echo "... edit_cache"
	@echo "... header/filehash.o"
	@echo "... header/filehash.i"
	@echo "... header/filehash.s"
	@echo "... src/bloomfilter.o"
	@echo "... src/bloomfilter.i"
	@echo "... src/bloomfilter.s"
	@echo "... src/bloomfiltertree.o"
	@echo "... src/bloomfiltertree.i"
	@echo "... src/bloomfiltertree.s"
	@echo "... src/filehash.o"
	@echo "... src/filehash.i"
	@echo "... src/filehash.s"
	@echo "... src/fingerprint.o"
	@echo "... src/fingerprint.i"
	@echo "... src/fingerprint.s"
	@echo "... src/fingerprintList.o"
	@echo "... src/fingerprintList.i"
	@echo "... src/fingerprintList.s"
	@echo "... src/fnv.o"
	@echo "... src/fnv.i"
	@echo "... src/fnv.s"
	@echo "... src/hashing.o"
	@echo "... src/hashing.i"
	@echo "... src/hashing.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sdhash.o"
	@echo "... src/sdhash.i"
	@echo "... src/sdhash.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

